### ISSUE TITLE
Calculating Misclassification Rates on Test Set

### ISSUE THREAD

**Issue by youralien** [takerum/vat#1]
Would be very helpful to have code that calculates misclassification rates in a test.py script, so anyone could try to replicate the results that the paper obtained.  Especially since that code must already be written!

**Comment by takerum** [comment]
Hi!

Thank you for the comment!

I uploaded test.py and you can obtain the error rate on test set by following commands:

```
python train.py <filename>
python test.py <filename>
```

Best,

**Comment by youralien** [comment]
Thanks very much :+1: Probably should update the README with this new information for anyone else!
